/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_f_project;

import java.sql.*;
import java.util.ArrayList;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ok
 */
public class RegisterForm extends javax.swing.JFrame {

    DefaultTableModel dtm;
    Connection con;
    ArrayList<Integer> dept_ids = new ArrayList<>();
    ArrayList<Integer> emp_ids = new ArrayList<>();

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        dtm = new DefaultTableModel();
        dtm.addColumn("NAME");
        dtm.addColumn("COLOR");
        dtm.addColumn("MODEL");
        dtm.addColumn("COST");

        
        try {
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agance", "root", "Rawan@12345");
         } catch (SQLException ex) {
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }   
            
            
        
        fillTableModel();

    }

   
   

    private void fillTableModel() {

        try {
            dtm.setRowCount(0);
            PreparedStatement stmt = con.prepareStatement("select car_name,carcolor,carmodel,carcost from cartype");
            ResultSet res = stmt.executeQuery();
            while (res.next()) {
                
                Object[] data = new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4)};
                dtm.addRow(data);
            }
            show_data.setModel(dtm);

        } catch (SQLException ex) {
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emp_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        emp_salary = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emp_dept = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        show_data = new javax.swing.JTable();
        back = new javax.swing.JButton();
        emp_register = new javax.swing.JButton();
        rbtn_male = new javax.swing.JRadioButton();
        rbtn_femal = new javax.swing.JRadioButton();
        emp_update = new javax.swing.JButton();
        emp_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Now");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Employee Name");

        emp_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emp_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Employee salary");

        emp_salary.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emp_salary.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Employee Department");

        emp_dept.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Employee gender");

        show_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        show_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(show_data);

        back.setBackground(new java.awt.Color(255, 102, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        emp_register.setBackground(new java.awt.Color(255, 102, 0));
        emp_register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emp_register.setText("Register");
        emp_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_registerActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn_male);
        rbtn_male.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtn_male.setSelected(true);
        rbtn_male.setText("Male");

        buttonGroup1.add(rbtn_femal);
        rbtn_femal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtn_femal.setText("Female");

        emp_update.setBackground(new java.awt.Color(255, 102, 0));
        emp_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emp_update.setText("Update");
        emp_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_updateActionPerformed(evt);
            }
        });

        emp_delete.setBackground(new java.awt.Color(255, 102, 0));
        emp_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emp_delete.setText("Delete");
        emp_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(emp_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(57, 57, 57)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emp_name, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(rbtn_male, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(rbtn_femal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(emp_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(emp_register, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emp_update, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(emp_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbtn_male)
                    .addComponent(rbtn_femal))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(emp_update)
                    .addComponent(emp_delete)
                    .addComponent(emp_register))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emp_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_registerActionPerformed
        // TODO add your handling code here:

        if (!emp_name.getText().isEmpty() && emp_salary.getText().length() > 0) {
            try {
                String employee_name = emp_name.getText();
                int employee_salary = Integer.parseInt(emp_salary.getText());
                String employee_gender;
                if (rbtn_male.isSelected()) {
                    employee_gender = "Male";
                } else {
                    employee_gender = "Female";
                }

                String employee_dept = String.valueOf(emp_dept.getSelectedItem());
             
                PreparedStatement stmt = con.prepareStatement("insert into employees(emp_name,emp_salary,emp_gender,dept_id) values(?,?,?,?)");
                stmt.setString(1, employee_name);
                stmt.setInt(2, employee_salary);
                stmt.setString(3, employee_gender);
                stmt.setInt(4, dept_ids.get(emp_dept.getSelectedIndex()));
                int res = stmt.executeUpdate();
                if (res > 0) {
                    JOptionPane.showMessageDialog(this, "Successed insert");
                    fillTableModel();
                } else {
                    JOptionPane.showMessageDialog(this, "Faild insert");
                }
////
            } catch (SQLException ex) {
                Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_emp_registerActionPerformed

    private void show_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_dataMouseClicked

        emp_name.setText(show_data.getValueAt(show_data.getSelectedRow(), 0).toString());
        emp_salary.setText(show_data.getValueAt(show_data.getSelectedRow(), 1).toString());
//
        String gender = show_data.getValueAt(show_data.getSelectedRow(), 2).toString();
        if (show_data.getValueAt(show_data.getSelectedRow(), 2).toString() == "Male") {
            rbtn_male.setSelected(true);
            }
        else {
            rbtn_femal.setSelected(true);
        }
//
        emp_dept.setSelectedItem(show_data.getValueAt(show_data.getSelectedRow(), 3));
//
//
    }//GEN-LAST:event_show_dataMouseClicked

    private void emp_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_updateActionPerformed

        if (!emp_name.getText().isEmpty() && emp_salary.getText().length() > 0) {

            try {
                String employee_name = emp_name.getText();
                int employee_salary = Integer.parseInt(emp_salary.getText());
                String employee_gender;
                if (rbtn_male.isSelected()) {
                    employee_gender = "Male";
                } else {
                    employee_gender = "Femal";
                }

                String employee_dept = String.valueOf(emp_dept.getSelectedItem());
                PreparedStatement stmt = con.prepareStatement("update employees set emp_name=?,emp_salary=?,emp_gender=?,dept_id=? where emp_id=?");
                stmt.setString(1, employee_name);
                stmt.setInt(2, employee_salary);
                stmt.setString(3, employee_gender);
                stmt.setInt(4, dept_ids.get(emp_dept.getSelectedIndex()));
                stmt.setInt(5, emp_ids.get(show_data.getSelectedRow()));
                int res = stmt.executeUpdate();
                if (res > 0) {
                    JOptionPane.showMessageDialog(this, "Successed updated");
                    fillTableModel();
                } else {
                    JOptionPane.showMessageDialog(this, "Faild insert");
                }

// TODO add your handling code here:
            } catch (SQLException ex) {
                Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_emp_updateActionPerformed
    }
    private void emp_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_deleteActionPerformed
        try {
            // TODO add your handling code here
            String employee_dept = String.valueOf(emp_dept.getSelectedItem());

            PreparedStatement stmt = con.prepareStatement("delete from employees where emp_id=?");
            stmt.setInt(1, emp_ids.get(show_data.getSelectedRow()));
            int res = stmt.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Successed deleted");
                fillTableModel();
            } else {
                JOptionPane.showMessageDialog(this, "Faild insert");
            }

        } catch (SQLException ex) {
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_emp_deleteActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        login l = new login();
        l.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton emp_delete;
    private javax.swing.JComboBox<String> emp_dept;
    private javax.swing.JTextField emp_name;
    private javax.swing.JButton emp_register;
    private javax.swing.JTextField emp_salary;
    private javax.swing.JButton emp_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtn_femal;
    private javax.swing.JRadioButton rbtn_male;
    private javax.swing.JTable show_data;
    // End of variables declaration//GEN-END:variables
}
